### PR TITLE
Modify partition oids in hypo_expand_partitioned_entry()

### PR DESCRIPTION
**Pull request by yuzupy**
I found that partition oids, which are got by hypo_find_inheritance_children(), are not sorted correctly.  I think they should be sorted according to partition bound just like the last part of hypo_generate_partitiondesc().  Otherwise, when not creating hypothetical partitions in partition bound order, results would be wrong because each RelOptInfo rel->relid would not be correct.
So I changed List *inhoids for Oid *partoids which are got by hypo_generate_partitiondesc().

### CODE REVIEW

**Comment by rjuju** [comment]
Ah indeed, nice catch!

Do you have a test case that fails with the old code that we could add to the regression tests?  Otherwise I'll try to come up with one.

**Comment by rjuju** [comment]
Thanks a lot!  I think that we don't need to test this behavior with all partitioning kind, the regression tests are already quite long.

The following test, extracted for the 2nd commit, demonstrates the problem:

```sql
DROP EXTENSION IF EXISTS hypopg;
CREATE EXTENSION hypopg;
DROP TABLE IF EXISTS hypo_part_range;
CREATE TABLE hypo_part_range (id integer, val text);
INSERT INTO hypo_part_range SELECT i, 'line ' || i FROM generate_series(1, 29999) i;
SELECT * FROM hypopg_partition_table('hypo_part_range', 'PARTITION BY RANGE (id)');
SELECT tablename FROM hypopg_add_partition('hypo_part_range_1_10000', 'PARTITION OF hypo_part_range FOR VALUES FROM (1) TO (10000)');
SELECT tablename FROM hypopg_add_partition('hypo_part_range_10000_20000', 'PARTITION OF hypo_part_range FOR VALUES FROM (10000) TO (20000)');
SELECT tablename FROM hypopg_add_partition('hypo_part_range_20000_30000', 'PARTITION OF hypo_part_range FOR VALUES FROM (20000) TO (30000)');
EXPLAIN SELECT * FROM hypo_part_range WHERE id = 42;
SELECT * FROM hypopg_reset();
SELECT * FROM hypopg_partition_table('hypo_part_range', 'PARTITION BY RANGE (id)');
SELECT tablename FROM hypopg_add_partition('hypo_part_range_10000_20000', 'PARTITION OF hypo_part_range FOR VALUES FROM (10000) TO (20000)');
SELECT tablename FROM hypopg_add_partition('hypo_part_range_20000_30000', 'PARTITION OF hypo_part_range FOR VALUES FROM (20000) TO (30000)');
SELECT tablename FROM hypopg_add_partition('hypo_part_range_1_10000', 'PARTITION OF hypo_part_range FOR VALUES FROM (1) TO (10000)');
EXPLAIN SELECT * FROM hypo_part_range WHERE id = 42;
```

which on current partitioning branch outputs:

```
[...]
                                          QUERY PLAN                                          
----------------------------------------------------------------------------------------------
 Append  (cost=0.00..2.29 rows=1 width=36)
   ->  Seq Scan on hypo_part_range hypo_part_range_1_10000  (cost=0.00..2.29 rows=1 width=36)
         Filter: (id = 42)
(3 rows)

 hypopg_reset 
--------------
 
(1 row)
[...]

                                            QUERY PLAN                                            
--------------------------------------------------------------------------------------------------
 Append  (cost=0.00..2.29 rows=1 width=36)
   ->  Seq Scan on hypo_part_range hypo_part_range_10000_20000  (cost=0.00..2.29 rows=1 width=36)
         Filter: (id = 42)
(3 rows)
```

I think that just adding hypo_part_range hypo_part_range_1_10000 after the other two hypothetical partitions in current's test on partitioning branch is enough to test the fix.  What do you think?

**Comment by yuzupy** [comment]
Thank you for the comments!
I agree with you, and I fixed the 2nd commit.
How does that look?

**Comment by rjuju** [comment]
That's perfect, thanks a lot!

**Pull request merged**
